name: Run a script

on:
  push

jobs:
  assign_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List repo files
      uses: ls
      
    - name: Execute shell script
      run: ./asciiii.sh